[".config/gitalias/gitalias.txt"]
type = "file"
url = "https://github.com/GitAlias/gitalias/raw/refs/heads/main/gitalias.txt"

[".zsh/.kubectl_aliases.sh"]
type = "file"
url = "https://github.com/ahmetb/kubectl-aliases/raw/refs/heads/master/.kubectl_aliases"

[".local/bin/defaults-diff"]
type = "file"
url = "https://raw.githubusercontent.com/yannbertrand/macos-defaults/refs/heads/main/diff.sh"
executable = true

### ? OMZ ###

[".zsh/ohmyzsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

[".zsh/ohmyzsh/custom/plugins/forgit"]
type = "archive"
url = "https://github.com/wfxr/forgit/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

[".zsh/ohmyzsh/custom/plugins/fzf-tab"]
type = "archive"
url = "https://github.com/Aloxaf/fzf-tab/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

[".zsh/ohmyzsh/custom/plugins/you-should-use"]
type = "archive"
url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

[".zsh/ohmyzsh/custom/plugins/zsh-autosuggestions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

[".zsh/ohmyzsh/custom/plugins/zsh-completions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

[".zsh/ohmyzsh/custom/plugins/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"

### ? YAZI ###

[".config/yazi/plugins"]
type = "archive"
url = "https://github.com/yazi-rs/plugins/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"
include = ["*/git.yazi/**", "*/no-status.yazi/**"]

[".config/yazi/plugins/ouch.yazi"]
type = "archive"
url = "https://github.com/ndtoan96/ouch.yazi/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "672h"
